### ISSUE TITLE
Feature: Adding a barcode scanner to the shift admin page

### ISSUE THREAD

**Issue by KiOui** [KiOui/TOSTI#123]
For scanning barcodes of soda cans or chocolate bars (etc.).

**Comment by KiOui** [comment]
This seems promising https://serratus.github.io/quaggaJS/

**Comment by JobDoesburg** [comment]
Yo vet ik wist niet dat mobile browsers dit supporten

**Comment by JobDoesburg** [comment]
So I guess we must 

- [ ] make a new kind of product (VendingProduct vs TakeawayProduct?)
- [ ] only have orders of TakeawayProduct appear in the queue, count towards capacity, etc
- [ ] have orders of TakeawayProduct automatically be set 'delivered'
- [ ] add a VendingProduct view for shift admins to the admin shift footer menu with the QuaggaJS library, creating orders after scanning (orders already do not require users)

So in the end, because we did quite a good software architecture job, it is not too hard to build this. Main focus is to find out how to do the class hierarchy with the new kind of products and orders and how much inheritance we want.
