### ISSUE TITLE
Buttons for the stages of selling a tosti

### ISSUE THREAD

**Issue by dhoekstra2000** [KiOui/TOSTI#337]
It would be nice to have extra buttons for the stages of selling a TOSTI. Concretely, an extra button for a built to tosti and for a tosti which has been picked up are wanted by the tosticies.

**Comment by DeD1rk** [comment]
I suggest replacing `Order.ready` with `Order.status` as TextChoices `{pending, baking, ready, picked_up}`. `Order.ready_at` is not used, so can probably be dropped. 

This would be a quite large change:
- the UI needs to be updated significantly to reflect the different statuses.
- the API should probably get a normal PATCH implementation, rather than a toggle endpoint. (This is a good idea anyway, as toggling is strange, not RESTful and causes unwanted behaviour when you (or two tosticie members) tap `paid` or `ready` twice.)

**Comment by KiOui** [comment]
I like the idea of creating a PATCH endpoint for toggling the paid and ready switches but I don't see how the extra buttons will fit in the interface. I don't think we will have enough space on the screen of a phone to add these types of buttons.

**Comment by DeD1rk** [comment]
With the `status` implementation, you could simply make them dropdowns or a tri(4?)-state button (so pressing cycles through states).

**Comment by wkuijltjes** [comment]
I would like to +1 this issue, I think it is the most requested feature among Tosticie Zuid members. A cycling toggle state would be fine already.
But as probably only the people that order the tostis use their phone it would probably also work when the admin view displays the different choices for the state and that only the one selected is displayed to the users, I wouldn't bother too much about screen space on a phone maybe.

**Comment by wkuijltjes** [comment]
I realise now that if this is considered a too big change, that an easier "fix" for the short term might be an admin-only button that allows tosticie members to toggle that a tosti has been "built" (so: bread, bread, cheese, ham --> bread, cheese, ham, bread). Especially if then the count of built tostis can be implemented in the shift summary such that you can see how many more tostis have to be prepared (since the baking of the tostis itself isn't too difficult in terms of administration, but Tosticie Zuid likes to be able to keep track how many tostis still have to be made).

**Comment by wkuijltjes** [comment]
Maybe it is easiest and thus best for now to add a small box on the left hand side that can be checked and is only visible for the Tosticie? That way, the Tosticie can keep track of which tosti's they have already "made" and it is easier to quickly see how many tosti's of each kind still has to be built. This method has always been used on the physical lists (by e.g. writing a small dot/mark in the row of an order that has been prepared. If this is not wanted and not preferred in North, then perhaps one can add the possibility to choose to add this in your overview when creating the shift.
An example of how it might look:
![tosti](https://user-images.githubusercontent.com/75427959/200848677-0171bc17-d55d-4a66-ae16-d43e69abaa45.png)
