### ISSUE TITLE
Manual adding weekly biermiddag

### ISSUE THREAD

**Issue by isavervuurt** [KiOui/TOSTI#389]
I have to reserve the same borrel and the south canteen every single week, could this process be automatized? Because it's a big chore to do this manually every single week.

**Comment by KiOui** [comment]
I think this is not something we should build into TOSTI, we might however be able to add an API endpoint for borrel reservations (so then you could interface via the API). For now it might be the best option to just create a script that POSTs the same form with different dates?

**Comment by JobDoesburg** [comment]
We could think about creating a button for copying the reserved amounts from the previous reservation, but only if it would be minimal code

**Comment by KiOui** [comment]
I'm more in favor of the API endpoint actually. @JobDoesburg do you think that is a lot of work (because of the complexity of the borrel reservations)?

**Comment by JobDoesburg** [comment]
> I'm more in favor of the API endpoint actually. @JobDoesburg do you think that is a lot of work (because of the complexity of the borrel reservations)?

It won't be an easy API endpoint, but it is possible. I wouldn't be in favor of making an API endpoint for this, mostly because it will probably really never be used by anyone, and it is quite an important extra part of logic that needs to be maintained (but probably won't). And any changes to the borrel reservation flow should thus be implemented twice (which we will probably forget)...
