### ISSUE TITLE
Submit borrel before end time

### ISSUE THREAD

**Issue by dhoekstra2000** [KiOui/TOSTI#416]
Currently, it is not possible to submit a borrelform before the end time of the borrel. However, some people enter a later time than they actually finish (e.g. because at the time they reserve, they are not sure when the borrel will end). Could this be changes such that submission before the end time is also possible?

**Comment by JobDoesburg** [comment]
This should already be possible, we only prevent submitting before the start time of a reservation (https://github.com/KiOui/TOSTI/blob/4cfe3e828063b6a67effcbfb2254e247a1b074ed/website/borrel/models.py#L151C11-L153), especially because not all borrels actually need an end time. Are you sure that this is actually true?

**Comment by dhoekstra2000** [comment]
I tested it, and it is indeed possible.
