### ISSUE TITLE
Notifying Technicie about need for music keys

### ISSUE THREAD

**Issue by dhoekstra2000** [KiOui/TOSTI#455]
It would be nice if with a reservation it could also be added that the music keys are needed with a checkbox. Furthermore, it would be nice if the Technicie gets an email about the borrels that tick this box.

**Comment by KiOui** [comment]
I think it is better to let the Voorraadcie also hand out the keys, whenever they are requested at a borrel. Otherwise two separate people need to meet up with the person that is going to hold the borrel. This also means that we do not have to implement another separate email that goes to a different party.
