### ISSUE TITLE
Implement synchronisation to Silvasoft

### ISSUE THREAD

**Issue by KiOui** [KiOui/TOSTI#456]
Tartarus is switching its administration from [Tantalus](https://github.com/thijsmie/tantalus) to [Silvasoft](https://www.silvasoft.nl). We should therefor provide support for synchronising `Shift`s and `BorrelReservation`s to Silvasoft. We should also remove the synchronisation to Tantalus.

Details for the Silvasoft API can be located [here](https://developers.silvasoft.nl).

**Comment by KiOui** [comment]
@dhoekstra2000 Could you provide us with a plan as to how you would want to switch to Silvasoft? E.g. when do we need to switch over the Tantalus synchronisation to Silvasoft synchronisation? How would you want to see it implemented (I assume just in the same way as we did with Tantalus)?

**Comment by dhoekstra2000** [comment]
So in short the transition will be tomorrow... This is for administrative purposes, since tomorrow the next VAT-quarter starts.

However, before the synchronisation could be implemented, the data has to be transferred from Tantalus and Conscribo to Silvasoft I suppose, which will be done from tomorrow onwards, and is hopefully done during the next week.

I will look if it is possible to have a test account development purposes.

Finally, how I would like to see it implemented, is basically the following:
- Every borrel is pushed as an invoice to Silvasoft.
- Every tostishift is pushed as an invoice to Silvasoft.
It would be nice if a "cost center" could be set for this ("Borrel" for borrels and "Tosti" for the tosti's themselves, "Kantine" for the candy and soda cans)

**Comment by dhoekstra2000** [comment]
About a test account, Silvasoft indicated this:
> Hiervoor kunnen de ontwikkelaars het beste een nieuwe proefaccount aanvragen via onze site, dan kunnen ze daarna de koppeling testen.

So you can make a trial account to test the synchronisation.
